# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
