# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('schedule', '0002_auto_20170520_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
            preserve_default=False,
        ),
    ]
