# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='places',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
