# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20170502_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_free',
        ),
    ]
